src/Entity/GpuOffer.php
<?php

namespace App\Entity;

use App\Repository\GpuOfferRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GpuOfferRepository::class)]
class GpuOffer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $brand = null;

    #[ORM\Column(length: 255)]
    private ?string $model = null;

    #[ORM\Column(length: 255)]
    private ?string $manufacturer = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Offer $offer = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getManufacturer(): ?string
    {
        return $this->manufacturer;
    }

    public function setManufacturer(string $manufacturer): self
    {
        $this->manufacturer = $manufacturer;

        return $this;
    }

    public function getOffer(): ?Offer
    {
        return $this->offer;
    }

    public function setOffer(Offer $Offer): self
    {
        $this->offer = $Offer;

        return $this;
    }
}

src/Entity/Offer.php
<?php

namespace App\Entity;

use App\Repository\OfferRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use \Datetime;
use DateTimeImmutable;

#[ORM\Entity(repositoryClass: OfferRepository::class)]
class Offer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(length: 255)]
    private ?string $img = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'offers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function __construct()
    {
        $this->createdAt = new DateTimeImmutable();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
    public function getCreatedAgo(): String
    {
        $current = new DateTime();
        $diff = $current->diff($this->createdAt);
        
        if($diff->days > 1)
        {
            return $diff->days . " dni";
        }
        if($diff->h > 0)
        {
            return $diff->h . " godz.";
        }
        if($diff->i > 0)
        {
            return $diff->i . " min.";
        }
        return "nowe";
        
    }
}

src/Form/GpuOfferType.php
<?php

namespace App\Form;

use App\Entity\GpuOffer;
use App\Service\GpuOfferService;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class GpuOfferType extends AbstractType
{
    private GpuOfferService $gpuOfferService;

    public function __construct(GpuOfferService $gpuOfferService)
    {
        $this->gpuOfferService = $gpuOfferService;    
    }
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('brand', ChoiceType::class,[
                'label' => false,
                'choices' => array_combine($this->gpuOfferService->GetBrands(), $this->gpuOfferService->GetBrands()),
                'attr' => [
                    'class' => 'select',
                ],
            ])
            ->add('model', ChoiceType::class,[
                'label' => false,
                'choices' => array_combine($this->gpuOfferService->GetModels(), $this->gpuOfferService->GetModels()),
                'attr' => [
                    'class' => 'select',
                ],
            ])
            ->add('manufacturer', ChoiceType::class,[
                'label' => false,
                'choices' => array_combine($this->gpuOfferService->GetManufacturers(), $this->gpuOfferService->GetManufacturers()),
                'attr' => [
                    'class' => 'select',
                ],
            ])
            ->add('offer',OfferType::class, [
                'label' => false,  
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => GpuOffer::class,
        ]);
    }
}

src/Controller/GpuOfferController.php
<?php

namespace App\Controller;


use App\Entity\GpuOffer;
use App\Form\GpuOfferType;
use App\Service\GpuOfferService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\String\Slugger\SluggerInterface;

class GpuOfferController extends AbstractController
{
    private EntityManagerInterface $em;
    private GpuOfferService $gpuOfferService;

    public function __construct(EntityManagerInterface $em, GpuOfferService $gpuOfferService)
    {
        $this->em = $em;
        $this->gpuOfferService = $gpuOfferService;
    }

    #[Route('/karty-graficzne', name: 'app_gpu_offer')]
    public function index(Request $request): Response
    {
        $pageParam = $request->query->get('page');
        $orderParam = $request->query->get('orderby');
        $priceFromParam = (float) $request->query->get('price_from');
        $priceToParam = (float) $request->query->get('price_to');
        $manufacturerParam = $request->query->all('manufacturer');
        $brandParam = $request->query->all('brand');
        $orderArr = explode('_', $orderParam);
        $modelParam =  $request->query->all('model');
        if($orderParam == null)
        {
            $orderArr[0] = 'createdAt';
            $orderArr[1] = 'desc';
        }
        $page = $pageParam == null ? "1" : $pageParam;

        $result = $this->gpuOfferService->getOffers($page, $modelParam, $brandParam, $manufacturerParam, $priceToParam, $priceFromParam, $orderArr[0], $orderArr[1]);
        
        $offers = $result[0];
        //$count = $result[1];
        $lastPage = $result[2];     $brands = $this->gpuOfferService->GetBrands();
        $manufacturers = $this->gpuOfferService->GetManufacturers();
        $models = $this->gpuOfferService->GetModels();

        return $this->render('gpu_offer/index.html.twig', [
            'offers' => $offers,
            'lastPage' => $lastPage,
            'currentPage' => $page,
            'orderSelected' => $orderParam,
            'priceFrom' => $priceFromParam,
            'priceTo' => $priceToParam,
            'manufacturers' => $manufacturers,
            'brands' => $brands,
            'models' => $models,
            'maufacturersSelected' => $manufacturerParam,
            'brandSelected' => $brandParam,
            'modelsSelected' => $modelParam
        ]);

    }
    #[Route('dodaj-ogloszenie/karty-graficzne', name: 'app_gpu_offer_create')]
    public function Create(Request $request, UserInterface $user, SluggerInterface $slugger) : Response
    {
        $offer = new GpuOffer();
        $form = $this->createForm(GpuOfferType::class, $offer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $img = $form->get('offer')->get('img')->getData();
            $originalFilename = pathinfo($img->getClientOriginalName(), PATHINFO_FILENAME);
            // this is needed to safely include the file name as part of the URL
            $safeFilename = $slugger->slug($originalFilename);
            $newFilename = $safeFilename.'-'.uniqid().'.'.$img->guessExtension();

            try{
                $img->move($this->getParameter("uploads_dir"), $newFilename);

            }
            catch(FileException $e){

            }

            $offer2 = $offer->getOffer();
            $offer2->setUser($user);
            $offer2->setImg($newFilename);
            $offer = $offer->setOffer($offer2);
            $this->em->persist($offer);
            $this->em->flush();

            return $this->redirectToRoute('app_gpu_offer');

        }
        return $this->render('gpu_offer/create.html.twig', [
            'offerForm' => $form->createView(),
        ]);
    }
    #[Route('karty-graficzne/{id}', name: 'app_gpu_offer_detail',  requirements: ['id' => '\d+'])]
    public function Detail(int $id) : Response
    {
        $offer = $this->gpuOfferService->GetOffer($id);
        if($offer)
        {
            return $this->render('gpu_offer/detail.html.twig', [
                'offer' => $offer
            ]);
        }
        return $this->redirectToRoute('app_gpu_offer');
    }
    #[Route('karty-graficzne/usun/{id}', name: 'app_gpu_offer_delete',  requirements: ['id' => '\d+'])]
    public function Delete(int $id) : Response
    {
        $this->gpuOfferService->delete($id);
        return $this->redirectToRoute('app_gpu_offer');
    }
}

templates/gpu_offer/create.html.twig
{% extends 'layout.html.twig' %}
{% block content %}
<div class="form-wrap">
    {{ form_start(offerForm, { 'attr' : { 'class': 'add-form' } }) }}
    {{ form_row(offerForm.offer) }}
    <div class="form-select-row">
        {{ form_row(offerForm.brand) }}
        {{ form_row(offerForm.manufacturer) }}
        {{ form_row(offerForm.model) }}
    </div>
    <button type="submit" class="btn">Dodaj ogłoszenie</button>
    {{ form_end(offerForm) }}
</div>
{% endblock %}

templates/gpu_offer/detail.html.twig
{% extends 'layout.html.twig' %}
{% block content %}
<div class="section">
    <div class="offer-detail">
        <h1>{{offer.offer.title}}</h1>
        <p><span class="offer-detail-price">{{offer.offer.price}} zł</span> - {{offer.offer.location}} - {{offer.offer.createdAgo}}</p>
        <div class="img-container">
            <img class="offer-detail-img" src="{{ asset('uploads/' ~ offer.offer.img) }}" alt="offer">
        </div>
        
        <p class="offer-detail-description">{{offer.offer.description | nl2br}}</p>
        {% if app.user == offer.offer.user %}
        
            <a href="usun/{{offer.id}}">Usuń</a>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/gpu_offer/index.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
   
    <section class="section">
   
    <div class="item-list">
    <select class="order select" id="order">
        <option value="createdAt_desc" {% if (orderSelected == 'createdAt_desc' or orderSelected == null) %} selected='selected' {% endif %}>Najnowsze</option>
        <option value="price_asc" {% if orderSelected == 'price_asc' %} selected='selected' {% endif %}>Cena: rosnąco</option>
        <option value="price_desc" {% if orderSelected == 'price_desc' %} selected='selected' {% endif %}>Cena: malejąco</option>
    </select>
    {% for offer in offers %}
        <article class="offer" onclick="redirectToDetail({{offer.id}})">
            <img class="offer-img" src="{{ asset('uploads/' ~ offer.offer.img) }}" alt="img">
            <div class="offer-stats">
                <div class="offer-header">
                    <h3 class="offer-title">{{offer.offer.title}}</h3>
                </div>
                <div class="offer-fill"> </div>
                <p class="offer-price">{{ offer.offer.price }} zł</p>
                <div class="offer-footer">
                    <p class="offer-location">{{ offer.offer.location }} - {{ offer.offer.createdAgo }}</p>
                </div>
            </div>
        </article>
    {% endfor %}
        <div class="pagination">
            <p>
                {% if currentPage > 1 %}
                <a class="pagination-link" href="{{ path(app.request.attributes.get('_route'), app.request.query.all|merge({'page': currentPage-1})) }}">{{ '<' }}</a>
                {% endif %}
                {{ ' ' }} {{ currentPage }} {{ ' z ' }} {{ lastPage }}
                {% if currentPage < lastPage %}
                <a class="pagination-link" href="{{ path(app.request.attributes.get('_route'),
                    app.request.query.all|merge({'page': currentPage+1})) }}">{{ '>' }}</a>
                {% endif %}
            </p>
        </div>
    </div>
    <div class="filters">
        <form class="filters-form" method="get" id="filter">
            <h4 class="filter-title">Cena</h4>
            <div class="filters-range">
                <input class="filters-price" name="price_from" value="{{ priceFrom == 0 ? ' ' : priceFrom}}"/> - 
                <input class="filters-price" name="price_to" value="{{ priceTo == 0 ? ' ' : priceTo }}"/>
            </div>
            <hr></hr>
            <h4 class="filter-title">Producent</h4>
            <div>
                {% for manufacturer in manufacturers %}
                <div>
                    <input type="checkbox" name="manufacturer[]" value="{{ manufacturer }}" {% if manufacturer in maufacturersSelected  %} checked {% endif %}>
                    <label>{{ manufacturer | upper }}</label>
                </div>
            {% endfor %}
            </div>
            <hr></hr>
            <h4 class="filter-title">Marka</h4>
            <div>
            {% for brand in brands %}
                <div>
                    <input type="checkbox" name="brand[]" value="{{ brand }}" {% if brand in brandSelected  %} checked {% endif %}>
                    <label>{{ brand | upper }}</label>
                </div>
            {% endfor %}
            </div>
            <hr></hr>
            <h4 class="filter-title">Model</h4>
            <div>
            {% for model in models %}
                <div>
                    <input type="checkbox" name="model[]" value="{{ model }}" {% if model in modelsSelected  %} checked {% endif %}>
                    <label>{{ model | upper }}</label>
                </div>
            {% endfor %}
            </div>
            <button class="btn btn-filter">Filtruj</button>
        </form>
    </div>
    </section>
     <script>
        //sorting
        const orderSelect = document.getElementById("order");
        const url = window.location.href;
        

        orderSelect.addEventListener("change", function(){
            let newUrl = new URL(url);
            newUrl.searchParams.set('orderby', orderSelect.value);
            newUrl.searchParams.set('page', '1');

            window.location = newUrl.toString();
        })

        function redirectToDetail(id)
        {
            window.location = url + '/' + id;
        }

    </script>
{% endblock %}